name: 'Lint OpenAPI Specification 3'
author: 'Eveoh'
description: 'Lint OpenAPI Specification 3 files'
inputs:
  spec:
    description: 'Path of the OpenAPI Specification 3 file'
    required: true
  token:
    description: "Github token for posting the check run. Can be acquired using {{ secrets.GITHUB_TOKEN }}"
    required: true
  ruleset:
    description: "Path of the ruleset file"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
